# Generated by Django 4.1.2 on 2022-10-13 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={
                "ordering": ("-priority", "-created"),
                "verbose_name": "Задача",
                "verbose_name_plural": "Список задач",
            },
        ),
    ]
